version: 2
jobs:
  testFeatureBranchesReact:
    resource_class: large
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build react application Docker image
          no_output_timeout : 1h
          command: |
            docker run -e CI=true ulminase/hello-world:latest
      ###############################################################
  testFeatureBranchesExpress:
      resource_class: large
      docker:
        - image: docker:18.06.3-ce-git
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Build Express application Docker image
            no_output_timeout : 1h
            command: |
              docker run -e CI=true ulminase/hello-world:latest
  testFeatureBranchesReact1:
    resource_class: large
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build react application Docker image
          no_output_timeout : 1h
          command: |
            docker run -e CI=true ulminase/hello-world:latest
      
  testFeatureBranchesExpress1:
      resource_class: large
      docker:
        - image: docker:18.06.3-ce-git
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Build Express application Docker image
            no_output_timeout : 1h
            command: |
              docker run -e CI=true ulminase/hello-world:latest
  testFeatureBranchesReact2:
    resource_class: large
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build react application Docker image
          no_output_timeout : 1h
          command: |
            docker run -e CI=true ulminase/hello-world:latest
      
  
        
        
workflows:
  version: 2
  build_test_feature:
    jobs:
      - testFeatureBranchesReact:
          filters:
            branches:
              ignore:
                - main
                - master
      - testFeatureBranchesExpress:
          filters:
            branches:
              ignore:
                - main
                - master
      - testFeatureBranchesReact1:
          filters:
            branches:
              ignore:
                - main
                - master
      - testFeatureBranchesExpress1:
          filters:
            branches:
              ignore:
                - main
                - master
      - testFeatureBranchesReact2:
          filters:
            branches:
              ignore:
                - main
                - master
      
